### ISSUE TITLE
Error in Transforming coordinates

### ISSUE THREAD

**Issue by adamshephard** [DeepPathology/MIDOG_reference_docker#6]
Hi, 

When implementing this docker locally my code fails in the final stage of prediction on transforming the coordinates. E.g.:
```
world_coords = image_data.TransformContinuousIndexToPhysicalPoint(
  [c for c in coord]
)
```
The following error is then given:

```
Traceback (most recent call last):
  File "process.py", line 121, in <module>
    Mitosisdetection().process()
  File "/home/adams/anaconda3/envs/tf23/lib/python3.8/site-packages/evalutils/evalutils.py", line 183, in process
    self.process_cases()
  File "/home/adams/anaconda3/envs/tf23/lib/python3.8/site-packages/evalutils/evalutils.py", line 191, in process_cases
    self._case_results.append(self.process_case(idx=idx, case=case))
  File "process.py", line 74, in process_case
    scored_candidates = self.predict(input_image=input_image)
  File "process.py", line 105, in predict
    world_coords = input_image.TransformContinuousIndexToPhysicalPoint(
  File "/home/adams/anaconda3/envs/tf23/lib/python3.8/site-packages/SimpleITK/SimpleITK.py", line 3264, in TransformContinuousIndexToPhysicalPoint
    return _SimpleITK.Image_TransformContinuousIndexToPhysicalPoint(self, index)
TypeError: in method 'Image_TransformContinuousIndexToPhysicalPoint', argument 2 of type 'std::vector< double,std::allocator< double > > const &'
```

Please can someone advise? Thanks for your help.

Bets wishes,
Adam Shephard

**Comment by adamshephard** [comment]
I have just realized it's because the coordinates need to be integers not floats!

**Comment by maubreville** [comment]
Great you worked it out yourself :-) Sorry that we weren't able to reply to you earlier.
